name: devcontainer_build_publish
on:
  workflow_dispatch:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  call_devcontainer_build_publish:
    uses: datajoint/.github/.github/workflows/devcontainer-build-publish.yaml@main
    with:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}