name: u24_element_tag_to_release

on:
  push:
    tags:
      - '*.*.*'
      - 'test*.*.*'

anchor-dev-build-call: &dev-build-call
  uses: yambottle/djsciops-cicd/.github/workflows/u24_element_build.yaml@main

anchor-test-build-call: &test-build-call
  uses: yambottle/djsciops-cicd/.github/workflows/u24_element_build.yaml@main

anchor-prod-build-call: &prod-build-call
  uses: dj-sciops/djsciops-cicd/.github/workflows/u24_element_build.yaml@main

jobs:
  call_context_check:
    uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
  call_u24_elements_build_alpine:
    !!merge <<: *$STAGE-build-call
    with:
      py_ver: 3.9
      image: djbase