name: u24_element_release_call

on:
  workflow_run:
    workflows: ["u24_element_tag_to_release"]
    types:
      - completed

anchor-dev-release-call: &dev-release-call
  uses: yambottle/djsciops-cicd/.github/workflows/u24_element_release.yaml@main

anchor-test-release-call: &test-release-call
  uses: yambottle/djsciops-cicd/.github/workflows/u24_element_release.yaml@main

anchor-prod-release-call: &prod-release-call
  uses: dj-sciops/djsciops-cicd/.github/workflows/u24_element_release.yaml@main

anchor-dev-release-if: &dev-release-if
  if: >-
    github.event.workflow_run.conclusion == 'success' &&
    github.repository_owner == 'yambottle' &&
    !contains(github.event.workflow_run.head_branch, 'test')

anchor-test-release-if: &test-release-if
  if: >-
    github.event.workflow_run.conclusion == 'success' &&
    github.repository_owner == 'yambottle' &&
    !contains(github.event.workflow_run.head_branch, 'test')

anchor-prod-release-if: &prod-release-if
  if: >-
    github.event.workflow_run.conclusion == 'success' &&
    github.repository_owner == 'datajoint' &&
    !contains(github.event.workflow_run.head_branch, 'test')

jobs:
  call_context_check:
    uses: dj-sciops/djsciops-cicd/.github/workflows/context_check.yaml@main
  test_call_u24_elements_release_alpine:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      ( contains(github.event.workflow_run.head_branch, 'test') ||
      (github.event.workflow_run.event == 'pull_request'))
    !!merge <<: *$STAGE-release-call
    with:
      py_ver: 3.9
      twine_repo: testpypi
    secrets:
      TWINE_USERNAME: ${{secrets.TWINE_TEST_USERNAME}}
      TWINE_PASSWORD: ${{secrets.TWINE_TEST_PASSWORD}}
  
  call_u24_elements_release_alpine:
    !!merge <<: *$STAGE-release-if
    !!merge <<: *$STAGE-release-call
    with:
      py_ver: 3.9
    secrets:
      TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
      TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}